name = "poseidon2-fv"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Poseidon2Fv"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[require]]
name = "LeanZKCircuit_Plonky3"
git = "https://github.com/NethermindEth/LeanZKCircuit-Plonky3.git"
rev = "Dom/4.27.0"

[[require]]
name = "Poseidon.lean"
git = "https://github.com/NethermindEth/Poseidon.lean.git"
rev = "Dan/width16"

[[lean_lib]]
name = "Poseidon2Fv"
