import Mathlib.Tactic.Attr.Register

register_simp_attr Poseidon2_W24S11_constraints
register_simp_attr Poseidon2_W24S11_expressions
register_simp_attr Poseidon2_W24S11_air_simplification
register_simp_attr Poseidon2_W24S11_constraint_and_interaction_simplification
