import Mathlib.Tactic.Attr.Register

register_simp_attr Poseidon2_W16S7_constraints
register_simp_attr Poseidon2_W16S7_expressions
register_simp_attr Poseidon2_W16S7_air_simplification
register_simp_attr Poseidon2_W16S7_constraint_and_interaction_simplification
